// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_mnuvaWzSG-6QPbkmcussFPIZ1y9Q8YM',
    appId: '1:959386352278:web:4d3e16374cba38e558a0b7',
    messagingSenderId: '959386352278',
    projectId: 'helthcare-c39a0',
    authDomain: 'helthcare-c39a0.firebaseapp.com',
    storageBucket: 'helthcare-c39a0.appspot.com',
    measurementId: 'G-FG1W7Z5024',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7LlX_wQKHZTSkDNENbOhXu9tL-xNnGds',
    appId: '1:959386352278:android:65a198f852b2e17358a0b7',
    messagingSenderId: '959386352278',
    projectId: 'helthcare-c39a0',
    storageBucket: 'helthcare-c39a0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvpZTay_heZoWt6rnkSWL1nikegoZc2RA',
    appId: '1:959386352278:ios:a443794543279e7d58a0b7',
    messagingSenderId: '959386352278',
    projectId: 'helthcare-c39a0',
    storageBucket: 'helthcare-c39a0.appspot.com',
    iosClientId: '959386352278-a3hr4f222moabf0ci6si7sl3ma6agehb.apps.googleusercontent.com',
    iosBundleId: 'com.example.helthCareDoctor',
  );
}
